name: Post Request on Commit to Main

on:
  push:
    branches:
      - main

jobs:
  post-request:
    runs-on: ubuntu-latest
    steps:
      - name: Home update confirmation
        env:
          HOME_COMMIT_PREFIX: ${{ secrets.HOME_COMMIT_PREFIX }}
        if: startsWith(github.event.head_commit.message, env.HOME_COMMIT_PREFIX)
        run: |
          curl -X POST ${{ secrets.URL }} \
          -H 'Content-Type: application/json' \
          -d '{"auth": "${{ secrets.AUTH }}", "page": "home", "message": "${{ github.event.head_commit.message }}", "commit_url": "${{ github.event.compare }}"}'

      - name: People update confirmation
        env:
          PEOPLE_COMMIT_PREFIX: ${{ secrets.PEOPLE_COMMIT_PREFIX }}
        if: startsWith(github.event.head_commit.message, env.PEOPLE_COMMIT_PREFIX)
        run: |
          curl -X POST ${{ secrets.URL }} \
          -H 'Content-Type: application/json' \
          -d '{"auth": "${{ secrets.AUTH }}", "page": "people", "message": "${{ github.event.head_commit.message }}", "commit_url": "${{ github.event.compare }}"}'

      - name: Research update confirmation
        env:
          RESEARCH_COMMIT_PREFIX: ${{ secrets.RESEARCH_COMMIT_PREFIX }}
        if: startsWith(github.event.head_commit.message, env.RESEARCH_COMMIT_PREFIX)
        run: |
          curl -X POST ${{ secrets.URL }} \
          -H 'Content-Type: application/json' \
          -d '{"auth": "${{ secrets.AUTH }}", "page": "research", "message": "${{ github.event.head_commit.message }}", "commit_url": "${{ github.event.compare }}"}'

      - name: Awards update confirmation
        env:
          AWARDS_COMMIT_PREFIX: ${{ secrets.AWARDS_COMMIT_PREFIX }}
        if: startsWith(github.event.head_commit.message, env.AWARDS_COMMIT_PREFIX)
        run: |
          curl -X POST ${{ secrets.URL }} \
          -H 'Content-Type: application/json' \
          -d '{"auth": "${{ secrets.AUTH }}", "page": "awards", "message": "${{ github.event.head_commit.message }}", "commit_url": "${{ github.event.compare }}"}'

      - name: Community update confirmation
        env:
          COMMUNITY_COMMIT_PREFIX: ${{ secrets.COMMUNITY_COMMIT_PREFIX }}
        if: startsWith(github.event.head_commit.message, env.COMMUNITY_COMMIT_PREFIX)
        run: |
          curl -X POST ${{ secrets.URL }} \
          -H 'Content-Type: application/json' \
          -d '{"auth": "${{ secrets.AUTH }}", "page": "community", "message": "${{ github.event.head_commit.message }}", "commit_url": "${{ github.event.compare }}"}'

      - name: Join Us update confirmation
        env:
          JOIN_US_COMMIT_PREFIX: ${{ secrets.JOIN_US_COMMIT_PREFIX }}
        if: startsWith(github.event.head_commit.message, env.JOIN_US_COMMIT_PREFIX)
        run: |
          curl -X POST ${{ secrets.URL }} \
          -H 'Content-Type: application/json' \
          -d '{"auth": "${{ secrets.AUTH }}", "page": "join_us", "message": "${{ github.event.head_commit.message }}", "commit_url": "${{ github.event.compare }}"}'
